title: Croner

description: Cron for JavaScript and TypeScript

remote_theme: just-the-docs/just-the-docs

url: https://croner.56k.guru

aux_links:
  GitHub Repository: https://github.com/hexagon/croner
  NPM Library: https://npmjs.com/package/croner
  Deno Library: https://deno.land/x/croner

plugins:
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-sitemap
  
enable_copy_code_button: true

# color_scheme: dark

# Footer content
footer_content: "Copyright &copy; 2012-2023 Hexagon. Distributed by an <a href=\"https://github.com/hexagon/croner/tree/master/LICENSE\">MIT license.</a>"
last_edit_time_format: "%b %e %Y at %I:%M %p"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/hexagon/croner"
gh_edit_branch: "dev"
gh_edit_source: docs
gh_edit_view_mode: "tree"