name: Publish to jsr.io
on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: cross-org/workflows/.github/workflows/jsr-publish.yml@main